---
abstract: 'build messages from templates'
author:
  - 'This code was written in 2009 by Ricardo SIGNES.  It was based on a previous'
build_requires:
  Test::Deep: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Email::MIME::Kit
name: Email-MIME-Kit
no_index:
  directory:
    - inc
    - t
requires:
  Email::MIME::Creator: 1.455
  Email::MessageID: 1.4
  File::Basename: 0
  File::Spec: 0
  JSON: 2
  Moose: 0.65
  String::RewritePrefix: 0
  YAML::XS: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/rjbs/email-mime-kit
version: 2.001
